alvaro51star/CameraPrototype

CameraPrototype/Assets/Scenes/Pruebas/PruebasAlvaro.unity
CameraPrototype/Assets/Scenes/Pruebas/ScenaPrueba.unity

Feature prueba raul

---

CameraPrototype/Assets/_Scripts/Enemies/Stalker/StalkerBehaviour.cs
CameraPrototype/Assets/_Scripts/Player/EnemyRelated/WatchEnemy.cs

He cambiado un poco la funcionalidad de la vision para que sea algo mas correcta

Cambios en la funcionalidad de la vision al enemigo

---

CameraPrototype/Assets/Scenes/Blockout/Prototipo_V2.0.unity

Feature assets casa

---

CameraPrototype/Assets/Prefabs/InteractiveObjects/Cat.prefab
CameraPrototype/Assets/Scenes/Nivel_1.unity
CameraPrototype/Assets/_Scripts/InteractiveObjects/Cat/CatMovementController.cs

Ahora el gato se mueve por un trigger, en vez de por interacción

Cambio a que el gato se mueva por trigger, no por interacción

---

CameraPrototype/Assets/_Scripts/Player/PlayerBehaviour.cs

Pequeño cambio para arreglar que la E se veía cuando no se debía

Pequeño cambio para arreglar error de que se ve la E cuando no debe

---

CameraPrototype/Assets/_Scripts/Camera/Anomalies Camera/AnomaliesLink.cs
CameraPrototype/Assets/_Scripts/Camera/Anomalies Camera/AnomaliesLink.cs.meta
CameraPrototype/Assets/_Scripts/Camera/Anomalies Camera/AnomalyBehaviour.cs

Script que hace que si una anomalía se revele, otra obligatoriamente también, aunque no sea visible

Unir una anomalía a otra

---

CameraPrototype/Assets/_Scripts/Enemies/Stalker/StalkerBehaviour.cs
CameraPrototype/Assets/_Scripts/Player/EnemyRelated/WatchEnemy.cs

mejora de legibilidad en los scripts para el editor

Feature ia improvement

---

CameraPrototype/Assets/Prefabs/TestManager.prefab
CameraPrototype/Assets/Prefabs/TestManager.prefab.meta
CameraPrototype/Assets/_Scripts/Enemies/Stalker/StateMachine/PlayerCatchState.cs
CameraPrototype/Assets/_Scripts/Managers/GameManager.cs
CameraPrototype/Assets/_Scripts/Managers/TestingManager.cs

Hace falta testear y añadir el evento cuando se termina el nivel ganando

Testing manager completo

---

CameraPrototype/Assets/Prefabs/Eventos.meta
CameraPrototype/Assets/Prefabs/Eventos/Feel.meta
CameraPrototype/Assets/Prefabs/Eventos/Feel/EV_Sonido.prefab
CameraPrototype/Assets/Prefabs/Eventos/Feel/EV_Sonido.prefab.meta
CameraPrototype/Assets/Prefabs/Eventos/Luces.meta
CameraPrototype/Assets/Prefabs/Eventos/Luces/EV_Luz.prefab
CameraPrototype/Assets/Prefabs/Eventos/Luces/EV_Luz.prefab.meta
CameraPrototype/Assets/Prefabs/InteractiveObjects/Door.prefab
CameraPrototype/Assets/Prefabs/InteractiveObjects/MarcoPuerta_01.prefab
CameraPrototype/Assets/Resources/FotosNivel_1/Photo1.png
CameraPrototype/Assets/Resources/FotosNivel_1/Photo1.png.meta
CameraPrototype/Assets/Resources/FotosNivel_1/Photo2.png
CameraPrototype/Assets/Resources/FotosNivel_1/Photo2.png.meta
CameraPrototype/Assets/Scenes/Blockout/Prototipo_V2.0.unity
CameraPrototype/Assets/_Scripts/Eventos.meta
CameraPrototype/Assets/_Scripts/Eventos/EV_Luz.cs
CameraPrototype/Assets/_Scripts/Eventos/EV_Luz.cs.meta
CameraPrototype/Assets/_Scripts/Eventos/Feel.meta
CameraPrototype/Assets/_Scripts/Eventos/Feel/Sonido.meta
CameraPrototype/Assets/_Scripts/Eventos/Feel/Sonido/Feel_Sonido.cs
CameraPrototype/Assets/_Scripts/Eventos/Feel/Sonido/Feel_Sonido.cs.meta

luces en hard shadow y ajustar algunas paredes

Luces y ajustes

---

CameraPrototype/Assets/_Scripts/Dialogue/DialogueController.cs

Al terminar el tutorial activa animaciones

activa animaciones cuando se termina el tutorial

---

CameraPrototype/Assets/_Scripts/Dialogue/TriggerForDialogue.cs

Se desactiva el trigger una vez acaba el tutorial

Feature arreglar tutorial

---

CameraPrototype/Assets/Prefabs/UI/UI.prefab
CameraPrototype/Assets/Sprites/Interface/Menu_Win.png
CameraPrototype/Assets/Sprites/Interface/Menu_Win.png.meta

cambios en la ui

---

CameraPrototype/Assets/Prefabs/Eventos/Luces/EV_Luz.prefab
CameraPrototype/Assets/Scenes/Nivel_1.unity
CameraPrototype/Assets/_Scripts/Eventos/EV_Luz.cs

:p script de las luces cambiado

cambio en el script del evento de las luces

---

CameraPrototype/Assets/_Scripts/Dialogue/DialogueController.cs
CameraPrototype/Assets/_Scripts/Dialogue/TriggerForDialogue.cs

se desactiva despues de salir y se abren las puertas cuando acaba el texto

arreglar tutorial

---

CameraPrototype/Assets/Animations/Puertas_Level1/ANIMATION/DoorInteractive.anim
CameraPrototype/Assets/Prefabs/InteractiveObjects/PuertaAnomalia.prefab
CameraPrototype/Assets/Prefabs/InteractiveObjects/PuertaInterativa.prefab
CameraPrototype/Assets/Scenes/Pruebas/Miriam/MiriamPruebas_Nivel1.unity
CameraPrototype/Assets/_Scripts/InteractiveObjects/SpecificActions/Interaction_Door.cs

Cambios en la animación de las puertas y pomo subido

---

CameraPrototype/Assets/Prefabs/InteractiveObjects/Door.prefab
CameraPrototype/Assets/Prefabs/InteractiveObjects/PuertaAnomalia.prefab
CameraPrototype/Assets/Prefabs/InteractiveObjects/PuertaInterativa.prefab
CameraPrototype/Assets/Scenes/Blockout/Prototipo_V2.0.unity

Puertas a medias, me voy a comer luego vuelvo

---

CameraPrototype/Assets/Prefabs/UI/CameraUI_Canvas.prefab
CameraPrototype/Assets/_Scripts/Camera/CameraRollController.cs

Cambio a que los números de carrete sean blancos

cambiar de color el número de carrete

---

CameraPrototype/Assets/Prefabs/InteractiveObjects/CajaArena.prefab
CameraPrototype/Assets/Prefabs/InteractiveObjects/CajaFuerte.prefab
CameraPrototype/Assets/Prefabs/InteractiveObjects/Carrete.prefab
CameraPrototype/Assets/Prefabs/InteractiveObjects/Cat.prefab
CameraPrototype/Assets/Prefabs/InteractiveObjects/Figurita.prefab
CameraPrototype/Assets/Prefabs/InteractiveObjects/Llave.prefab
CameraPrototype/Assets/Prefabs/InteractiveObjects/Nota.prefab
CameraPrototype/Assets/Prefabs/InteractiveObjects/ObjetoMalditoFinal.prefab
CameraPrototype/Assets/Prefabs/Player.prefab
CameraPrototype/Assets/Prefabs/UI/UI.prefab
CameraPrototype/Assets/Scenes/Pruebas/Miriam/MiriamPruebasPrototipo.unity
CameraPrototype/Assets/Scenes/Pruebas/Miriam/MiriamPruebas_Nivel1.unity
CameraPrototype/Assets/_Scripts/InteractiveObjects/Cat/CatMovementController.cs
CameraPrototype/Assets/_Scripts/Managers/UI/UIManager.cs
CameraPrototype/Assets/_Scripts/Player/PlayerBehaviour.cs

Añadido acariciar al gato y su integración con interacción

---

CameraPrototype/Assets/Prefabs/InteractiveObjects/Cat.prefab
CameraPrototype/Assets/Prefabs/Player.prefab
CameraPrototype/Assets/_Scripts/InteractiveObjects/Cat/CatMovementController.cs
CameraPrototype/Assets/_Scripts/InteractiveObjects/Cat/GrowlTrigger.cs

Solamente se mueve si no hay obstáculos en su trayectoria. Al gruñir se coloca una posición para que la mire.

Feature arreglar gato

---

CameraPrototype/Assets/Scenes/Blockout/Prototipo_V2.0.unity
CameraPrototype/Assets/Scenes/MainMenuScene.unity
CameraPrototype/Assets/_Scripts/InteractiveObjects/Cat/GrowlTrigger.cs
CameraPrototype/Assets/_Scripts/Managers/UI/UIManager.cs

Feature UI

---

CameraPrototype/Assets/Animations/Cuadros/Cuadro.anim
CameraPrototype/Assets/Scenes/Blockout/Prototipo_V2.0.unity
CameraPrototype/Assets/_Scripts/ActivateSB.cs
CameraPrototype/Assets/_Scripts/ActivateSB.cs.meta

Animacion caja fuerte

---

CameraPrototype/Assets/Audio/Interactive/mlaudio_magicGameWin.wav
CameraPrototype/Assets/Audio/Interactive/mlaudio_magicGameWin.wav.meta
CameraPrototype/Assets/Scenes/Blockout/Prototipo_V2.0.unity

Feature 1collider

---

CameraPrototype/Assets/Prefabs/InteractiveObjects/Cat.prefab
CameraPrototype/Assets/_Scripts/Camera/Anomalies Camera/AnomalyBehaviour.cs
CameraPrototype/Assets/_Scripts/InteractiveObjects/Cat/CatMovementController.cs
CameraPrototype/Assets/_Scripts/Managers/EventManager.cs

Ahora se moverá por eventos, por lo que también he creado un evento para cuando se revela el enemigo

Cambios para el movimiento del gato

---

CameraPrototype/Assets/Prefabs/Player.prefab
CameraPrototype/Assets/_Scripts/Camera/PhotoCapture.cs

Cambios para que la foto se quite automáticamente tras un tiempo editable en el editor (ahora está en 2s)

Auto quitar foto

---

CameraPrototype/Assets/Prefabs/UI/UI.prefab
CameraPrototype/Assets/_Scripts/Dialogue/DialogueController.cs

Ya no cambia de línea de texto sin input. Cambios en el script y en el prefab de UI.

Tutorial ya no es auto

---

CameraPrototype/Assets/_Scripts/Camera/Anomalies Camera/AnomalyCameraManager.cs

Forzar a que el script que daba error busque la camara de anomalias cuando da null

Arreglar restart

---

CameraPrototype/Assets/_Scripts/Camera/Anomalies Camera/AnomalyCamTrigger.cs

Comprueba si el enemigo no esta atacando antes de hacer el stun

No stun al enemigo si está atacando

---

CameraPrototype/Assets/Animations/Cuadros/Cuadro.anim
CameraPrototype/Assets/Materials/Decals/MAT_Aranazos.mat
CameraPrototype/Assets/Materials/Decals/MAT_Aranazos.mat.meta

Cambios blockout

---

CameraPrototype/Assets/Scenes/Pruebas/Miriam/MiriamPruebasPrototipo.unity
CameraPrototype/Assets/_Scripts/InteractiveObjects/SpecificActions/Interaction_Door.cs

Se ha añadio una booleana a la puerta para marcarla como puerta de gato, si tiene eso activa, lanzará un evento al abrirse solo una vez

Añadido evento en puerta para el gato

---

CameraPrototype/Assets/Prefabs/Player.prefab
CameraPrototype/Assets/_Scripts/Camera/CameraRollController.cs
CameraPrototype/Assets/_Scripts/Dialogue/DialogueController.cs
CameraPrototype/Assets/_Scripts/Dialogue/TextForDialogue.cs
CameraPrototype/Assets/_Scripts/Dialogue/TextForDialogue.cs.meta
CameraPrototype/Assets/_Scripts/Dialogue/TriggerForDialogue.cs

Cambios en el funcionamiento del dialogo para poder usarlo sin trigger. Ahora se llama cuando te quedas sin fotos y te pone un texto.

Texto de no te quedan fotos

---

CameraPrototype/Assets/Input/PlayerInput.cs
CameraPrototype/Assets/Input/PlayerInput.inputactions
CameraPrototype/Assets/Prefabs/Player.prefab
CameraPrototype/Assets/Scenes/Pruebas/Miriam/MiriamPruebasPrototipo.unity
CameraPrototype/Assets/_Scripts/Camera/PhotoCapture.cs
CameraPrototype/Assets/_Scripts/Player/InputController.cs

+ Ya no hace take foto si no tiene la cámara puesta o está vieno la foto hecha

Añadido cheat para camera roll

---

CameraPrototype/Assets/Prefabs/InteractiveObjects/Cat.prefab

Puntos gato

---

CameraPrototype/Assets/Assets/Assets_Animacion/HUGO/LibritoParaRaul.fbx
CameraPrototype/Assets/Assets/Assets_Animacion/HUGO/LibritoParaRaul.fbx.meta
CameraPrototype/Assets/Materials/Decals/Mat_Poster.mat
CameraPrototype/Assets/Materials/Decals/Mat_Poster.mat.meta
CameraPrototype/Assets/Prefabs/InteractiveObjects/StoryBook.prefab

Colocacion de cosas

---

CameraPrototype/Assets/Prefabs/InteractiveObjects/BarbaRoja.prefab
CameraPrototype/Assets/Prefabs/InteractiveObjects/BarbaRoja.prefab.meta
CameraPrototype/Assets/Prefabs/InteractiveObjects/CajaArena.prefab
CameraPrototype/Assets/Scenes/Pruebas/Miriam/MiriamPruebasPrototipo.unity
CameraPrototype/Assets/_Scripts/InteractiveObjects/SpecificActions/Interaction_RedBeard.cs
CameraPrototype/Assets/_Scripts/InteractiveObjects/SpecificActions/Interaction_RedBeard.cs.meta
CameraPrototype/Assets/_Scripts/Player/PlayerBehaviour.cs

También se ha añadido en la caja de arena que cuando se coloca a Barbaverde se lea texto que diga barbaverde

Añadido barbaroja que al mirarlo tiene mensaje

---

CameraPrototype/Assets/Prefabs/Managers/AlbumManager.prefab
CameraPrototype/Assets/Prefabs/Managers/AlbumManager.prefab.meta
CameraPrototype/Assets/Prefabs/UI/UI.prefab
CameraPrototype/Assets/Scenes/Pruebas/Miriam/MiriamPruebasPrototipo.unity
CameraPrototype/Assets/Sprites/Interface/album.png.meta
CameraPrototype/Assets/_Scripts/Camera/Inventario/AlbumManager.cs
CameraPrototype/Assets/_Scripts/Camera/PhotoCapture.cs
CameraPrototype/Assets/_Scripts/Managers/UI/UIManager.cs

Funciona pero sprite siempre el mismo no se por qué

Comienzo Album

---

CameraPrototype/Assets/Prefabs/Player.prefab

Añadir script del album al jugador, agrandar un poco el trigger de la cámara y cambio en la escena (meter una referencia que le faltaba al jugador).

Feature modificar player prefab

---

CameraPrototype/Assets/Scenes/Nivel_1.unity
CameraPrototype/Assets/Volume.meta
CameraPrototype/Assets/Volume/FeelVolumeProfile.asset
CameraPrototype/Assets/Volume/FeelVolumeProfile.asset.meta
CameraPrototype/Assets/_Scripts/Eventos/Feel/EV_EnemigoTeVe.cs
CameraPrototype/Assets/_Scripts/Eventos/Feel/EV_EnemigoTeVe.cs.meta

pruebas feel, feedback visual

---

CameraPrototype/Assets/Prefabs/Player.prefab

Modificando el prefab del player

Bajar volumen del radar de anomalías

---

CameraPrototype/Assets/Prefabs/InteractiveObjects/Llave.prefab

Mover llave

---

CameraPrototype/Assets/_Scripts/Camera/Anomalies Camera/AnomalyBehaviour.cs
CameraPrototype/Assets/_Scripts/Camera/Anomalies Camera/AnomalyCamTrigger.cs
CameraPrototype/Assets/_Scripts/Camera/PhotoCapture.cs

Más comprobaciones con return, menos get component y menos comentarios en la cámara de anomalías

Feature optimizar camara

---

CameraPrototype/Assets/_Scripts/InteractiveObjects/SpecificActions/Interaction_CajaArena.cs
CameraPrototype/Assets/_Scripts/InteractiveObjects/SpecificActions/Interaction_CajaFuerte.cs
CameraPrototype/Assets/_Scripts/InteractiveObjects/SpecificActions/Interaction_Door.cs
CameraPrototype/Assets/_Scripts/InteractiveObjects/SpecificActions/Interaction_Notas.cs
CameraPrototype/Assets/_Scripts/InteractiveObjects/SpecificActions/Interaction_StoryBook.cs
CameraPrototype/Assets/_Scripts/InteractiveObjects/_Structure/InteractiveObject.cs

Marcado los puntos en los que hace falta lineas de fmod para sustituir otras

Comentarios para FMOD

---

CameraPrototype/Assets/Prefabs/Player.prefab
CameraPrototype/Assets/Scenes/Pruebas/Miriam/MiriamPruebas.unity.meta
CameraPrototype/Assets/_Scripts/Player/PlayerMovement.cs

Ajustado valores del script y la del character controller

Arreglado el movimiento del player

---

CameraPrototype/Assets/_Scripts/Camera/CameraManager.cs
CameraPrototype/Assets/_Scripts/Camera/PhotoCapture.cs

Si se quita manualmente la foto de la pantalla se para la corrutina de quitarla automáticamente

Arreglar bug de las fotos quitándose

---

CameraPrototype/Assets/_Scripts/Managers/UI/UIManager.cs
CameraPrototype/Assets/_Scripts/Player/PlayerMovement.cs

Sensibilidad raton

---

CameraPrototype/Assets/Input/PlayerInput.cs
CameraPrototype/Assets/Input/PlayerInput.inputactions
CameraPrototype/Assets/Prefabs/Player.prefab
CameraPrototype/Assets/Scenes/Pruebas/PruebasElena/PruebaLentePasado.unity.meta
CameraPrototype/Assets/_Scripts/Camera/CameraManager.cs
CameraPrototype/Assets/_Scripts/Camera/CameraRollController.cs
CameraPrototype/Assets/_Scripts/Camera/PhotoCapture.cs
CameraPrototype/Assets/_Scripts/InteractiveObjects/SpecificActions/Interaction_Cat.cs
CameraPrototype/Assets/_Scripts/Managers/EventManager.cs
CameraPrototype/Assets/_Scripts/Player/InputController.cs
CameraPrototype/ProjectSettings/TagManager.asset

Cambios para poder incluir más lentes y estandarización de las variables de los scripts de la cámara.

Feature prueba lente pasado
